### ISSUE TITLE
implement TNG-all

### ISSUE THREAD

**Issue by changhoonhahn** [galactic-ai/haloflow#8]
implement dataset that combines TNG50 + TNG100 (with mass corrections)

**Comment by changhoonhahn** [comment]
@cbottrell, I want to double check how I should implement the stellar mass corrections when combining TNG50 and TNG100. What exactly does the column `StellarMassResCorrection` correspond to? I assume its in dex? 

Assuming its in dex, I implemented a correction. Does the comparison below look sensible? 

![Image](https://github.com/user-attachments/assets/873bce2d-5702-44a7-9499-b0c0495ace31)
![Image](https://github.com/user-attachments/assets/ba858768-f374-4a50-bc32-652a344cbd39)

**Comment by cbottrell** [comment]
> @cbottrell, I want to double check how I should implement the stellar mass corrections when combining TNG50 and TNG100. What exactly does the column `StellarMassResCorrection` correspond to? I assume its in dex?
> 
> Assuming its in dex, I implemented a correction. Does the comparison below look sensible?

@changhoonhahn You should be able to just add these corrections (in dex) to the log stellar masses of TNG50 galaxies to match TNG100. So everything above is right except you have changed the TNG100 masses to match TNG50. Only the TNG100 model is calibrated to match the z=0 stellar mass function. So you should instead be adding these corrections to the TNG50 masses to match TNG100.

![SHMR](https://github.com/user-attachments/assets/d94ec86a-e554-413b-96bc-b81e18849fed)
![TNG_SHMR_Rescaling](https://github.com/user-attachments/assets/99a9f2aa-67a1-4502-8a04-8a417e57693b)

**Comment by changhoonhahn** [comment]
Gotcha. Thanks @cbottrell!

One additional question: in your email you mentioned `MagnitudeCorrection`. Where can I find that? It's not in the `StellarMassResCorrection_TNG50-1.csv` file and I don't see anything in the one drive.

**Comment by cbottrell** [comment]
The newest files have names like `HaloFlow_{simulation}.csv`. The last two columns of the TNG50 file are `StellarMassCorrection` and `MagnitudeCorrection`. None of the other tables have those two columns. The `StellarMassResCorrection_TNG50-1.csv` contains the boxcar-averaged offsets in stellar mass at a given TNG50 halo mass with respect to the averages in the corresponding TNG100 halo mass. I've used these to interpolate corrections at any halo mass in TNG50, and those are the values found in the `HaloFlow_{simulation}.csv` files.

**Comment by changhoonhahn** [comment]
Implemented TNG-All in [eeb9daa](https://github.com/galactic-ai/haloflow/commit/eeb9daa404213a02008fca2111f75e2538a8aa03)

Here's the SHMR of the joint sample: 
![image](https://github.com/user-attachments/assets/402086b3-8233-4bc9-8361-22ce80477011)
